### ISSUE TITLE
Proposition: migrate from `setup.py` to `pyproject.toml`

### ISSUE THREAD

**Issue by danroc** [LedgerHQ/ledgerctl#48]
What's you opinion about moving from `setup.py` to `pyproject.toml`? It's a declarative way to describe the project, and it can also store the configuration of other tools, like black, mypy, etc.

An option is to use [Flit](https://flit.pypa.io/en/stable/), it's very lightweight and simple to use.

WDYT?

**Comment by jibeee** [comment]
It is something I would like to do (and started it locally), but never got time to finalize it. Contributions are welcome :)
